OMEN_NAMES = (
    "Omen of Refreshment",
    "Omen of Resurgence",
    "Omen of Amelioration",
    "Omen of Whittling",
    "Omen of Sinistral Erasure",
    "Omen of Dextral Erasure",
    "Omen of Sinistral Alchemy",
    "Omen of Dextral Alchemy",
    "Omen of Sinistral Coronation",
    "Omen of Dextral Coronation",
    "Omen of Corruption",
    "Omen of Greater Exaltation",
    "Omen of Sinistral Exaltation",
    "Omen of Dextral Exaltation",
    "Omen of Greater Annulment",
    "Omen of Sinistral Annulment",
    "Omen of Dextral Annulment",
    "Omen of Answered Prayers",
    "Omen of Secret Compartments",
    "Omen of the Hunt",
    "Omen of Reinforcements",
    "Omen of Homogenising Exaltation",
    "Omen of Homogenising Coronation",
    "Omen of Gambling",
    "Omen of Bartering",
    "Omen of Recombination",
    "Omen of the Blessed",
    "Omen of Chaotic Rarity",
    "Omen of Chaotic Quantity",
    "Omen of Chaotic Monsters",
    "Omen of Chaotic Effectiveness",
    "Omen of Chance",
    "Omen of the Ancients",
    "Omen of Sanctification",
    "Omen of Dextral Crystallisation",
    "Omen of Sinistral Crystallisation",
    "Omen of Catalysing Exaltation",
    "Omen of Abyssal Echoes",
    "Omen of the Sovereign",
    "Omen of the Liege",
    "Omen of the Blackblooded",
    "Omen of Putrefaction",
    "Omen of Light",
    "Omen of Sinistral Necromancy",
    "Omen of Dextral Necromancy",
)
